const {app,BrowserWindow,dialog,ipcMain}=require('electron');
const fs=require('node:fs/promises');
const os=require('node:os');
const path=require('node:path');
const assert=require('node:assert/strict');
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function run() {
  const base=await fs.mkdtemp(path.join(os.tmpdir(),'blockit-map-'));
  app.setPath('userData',path.join(base,'profile'));
  const fixture=path.join(base,'Treemap sample');
  const folders=[['Games',54000],['Study videos',46000],['Projects',41000],['Photos',15000],['Downloads',10000],['Music',8000]];
  for(const [name,size] of folders) {
    await fs.mkdir(path.join(fixture,name),{recursive:true});
    await fs.writeFile(path.join(fixture,name,'sample.txt'),Buffer.alloc(size));
  }
  await fs.mkdir(path.join(fixture,'Games','Nested'),{recursive:true});
  await fs.writeFile(path.join(fixture,'Games','Nested','deep.txt'),Buffer.alloc(3000));
  await fs.writeFile(path.join(fixture,'empty.txt'),'');
  require('../dist-electron/main.js');
  await app.whenReady();
  let win;
  for(let i=0;i<100;i++) {
    win=BrowserWindow.getAllWindows()[0];
    if(win&&!win.webContents.isLoading()&&await win.webContents.executeJavaScript('!!document.querySelector(".welcome")').catch(()=>false)) break;
    await delay(100);
  }
  const js=code=>win.webContents.executeJavaScript('(()=>{'+code+'})()',true).catch(error=>{throw new Error(code+'\n'+error.message)});
  dialog.showOpenDialog=async()=>({canceled:false,filePaths:[fixture]});
  await js("Array.from(document.querySelectorAll('button')).find(b=>b.textContent.includes('Choose folder')).click()");
  for(let i=0;i<100;i++){if(await js('return !!document.querySelector(".completion-note")'))break;await delay(100);}
  if(process.env.BLOCKIT_FULLSCREEN_PREVIEW==='1') {
    await js('document.querySelector(".nav-item[aria-label=Treemap]").click()');await delay(600);
    await js('document.querySelector(".map-fullscreen-toggle").click()');
    win.show();win.focus();
    console.log('Fullscreen preview open with generated sample files.');
    return;
  }
  // Use a marked sample drive to verify free space stays out of the map without scanning a real drive.
  const scanFiles=await fs.readdir(path.join(base,'profile','scans'));
  const scanId=scanFiles.find(file=>file.endsWith('.db')).slice(0,-3);
  const summary=await win.webContents.executeJavaScript('window.blockit.data.summary('+JSON.stringify(scanId)+')');
  ipcMain.removeHandler('data:summary');
  ipcMain.handle('data:summary',()=>({...summary,rootPath:'Z:\\',volumeFreeBytes:39000}));
  win.webContents.send('scan:progress',{scanId,status:'completed',files:6,folders:7,bytes:174000,warnings:0,elapsedMs:500});
  await delay(400);
  await js("Array.from(document.querySelectorAll('.nav-item')).find(b=>b.textContent.includes('Treemap')).click()");
  await delay(600);
  assert.equal(await js("return document.querySelectorAll('.treemap-cell[data-kind=folder]').length"),6);
  assert.equal(await js("return new Set(Array.from(document.querySelectorAll('.treemap-cell[data-kind=folder] .block-outline')).map(r=>r.getAttribute('fill'))).size"),6,'Every folder is visibly distinct');
  assert.equal(await js("return document.querySelectorAll('[data-kind=free]').length"),0,'Free space is excluded even for drive roots');
  const deep=await win.webContents.executeJavaScript('window.blockit.data.treemap('+JSON.stringify(scanId)+','+summary.rootId+',3)');
  assert(deep.find(n=>n.name==='Games').children.find(n=>n.name==='Nested').children.some(n=>n.name==='deep.txt'),'Depth 3 loads grandchildren');
  await assert.rejects(win.webContents.executeJavaScript('window.blockit.data.treemap('+JSON.stringify(scanId)+','+summary.rootId+',4)'));
  for(const label of ['Types','Size','Age','Levels','Distinct']) {
    await js('Array.from(document.querySelectorAll(".map-segments button")).find(b=>b.textContent==='+JSON.stringify(label)+').click()');
    await delay(80);
    assert(await js('return document.querySelector(".map-legend").textContent.length>20'));
  }
  await js('Array.from(document.querySelectorAll(".map-segments button")).find(b=>b.getAttribute("aria-label")==="Show 3 levels").click()');
  await delay(500);
  assert(await js('return document.querySelectorAll(".treemap-cell").length>13'),'Nested rectangles rendered');
  await fs.writeFile(path.join(__dirname,'../docs/treemap-nested.png'),(await win.webContents.capturePage()).toPNG());
  await js('const input=document.querySelector(".map-size-filter input");Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value").set.call(input,"6");input.dispatchEvent(new Event("input",{bubbles:true}))');
  await delay(100);
  assert.equal(await js('return document.querySelectorAll(".treemap-cell[data-kind=folder]").length'),0,'Size filter hides small folders');
  assert(await js('return document.querySelector(".map-block-list").textContent.includes("empty.txt")'),'Zero-byte items remain accessible');
  await js('const input=document.querySelector(".map-size-filter input");Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value").set.call(input,"0");input.dispatchEvent(new Event("input",{bubbles:true}))');
  await js('Array.from(document.querySelectorAll(".map-segments button")).find(b=>b.getAttribute("aria-label")==="Show 1 levels").click()');
  await delay(500);
  await js("const first=document.querySelector('.treemap-cell'); first.focus()");
  await delay(100);
  assert(await js("return document.querySelector('.map-details').textContent.includes('Games')"),'Focus shows metadata');
  const gamesPath=path.join(fixture,'Games');
  assert.equal(await js('return document.querySelector(".map-path").textContent'),gamesPath,'Focus shows the full folder path');
  assert((await js('return document.querySelector(".treemap-cell title").textContent')).includes(gamesPath),'Hover tooltip includes the full path');
  // Exercise the real validated IPC action without replacing the user's clipboard.
  let copiedPath;
  require('electron').clipboard.writeText=value=>{copiedPath=value;};
  await js('document.querySelector(".map-copy-path").focus()');
  await delay(50);
  assert.equal(await js('return document.querySelector(".map-path").textContent'),gamesPath,'Moving keyboard focus to Copy preserves the displayed path');
  await js('document.querySelector(".map-copy-path").click()');
  for(let i=0;i<40&&!copiedPath;i++)await delay(50);
  assert.equal(copiedPath,gamesPath,'Copy sends the full path through the validated native clipboard action');
  assert.equal(await js('return document.querySelectorAll(".treemap-cell[data-kind=folder]").length'),6,'Copy does not navigate');
  await js('document.querySelectorAll(".treemap-cell")[1].dispatchEvent(new MouseEvent("mouseover",{bubbles:true}))');
  await delay(100);
  assert.equal(await js('return document.querySelector(".map-path").textContent'),path.join(fixture,'Study videos'),'Hover updates the full path');

  await js("const input=document.querySelector('.map-search input');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'Music');input.dispatchEvent(new Event('input',{bubbles:true}));");
  await delay(100);
  assert.equal(await js("return Array.from(document.querySelectorAll('.treemap-cell')).filter(cell=>cell.getAttribute('opacity')==='1').length"),1,'Search highlights one match without relayout');
  await js("document.querySelector('.treemap-cell').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))");
  await delay(100);
  await fs.mkdir(path.join(__dirname,'../docs'),{recursive:true});
  await fs.writeFile(path.join(__dirname,'../docs/treemap-light.png'),(await win.webContents.capturePage()).toPNG());
  const exportPath=path.join(base,'treemap-export.png');
  dialog.showSaveDialog=async()=>({canceled:false,filePath:exportPath});
  await js("Array.from(document.querySelectorAll('button')).find(b=>b.textContent.includes('Save image')).click()");
  for(let i=0;i<80;i++){if(await fs.stat(exportPath).then(s=>s.size>1000).catch(()=>false))break;await delay(100);}
  assert((await fs.stat(exportPath)).size>1000,'PNG export produced an image');
  await fs.copyFile(exportPath,path.join(__dirname,'../docs/treemap-export.png'));
  await js("Array.from(document.querySelectorAll('button')).find(b=>b.title==='Toggle theme').click()");
  await delay(200);
  await fs.writeFile(path.join(__dirname,'../docs/treemap-dark.png'),(await win.webContents.capturePage()).toPNG());
  await js("const first=document.querySelector('.treemap-cell');first.focus();first.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));");
  await delay(400);
  assert(await js("return document.querySelector('.treemap-panel h2').textContent.includes('Games')"),'Enter drills into folder');
  await js('document.querySelector(".treemap-cell[data-kind=folder]").dispatchEvent(new MouseEvent("click",{bubbles:true}))');await delay(300);
  assert.equal(await js('return document.querySelector(".treemap-panel h2").textContent'),'Nested');
  await js('document.querySelector(".map-back").click()');await delay(300);
  assert.equal(await js('return document.querySelector(".treemap-panel h2").textContent'),'Games','Normal back returns one folder, not root');
  await js("Array.from(document.querySelectorAll('button')).find(b=>b.textContent.includes('Back to root')).click()");
  await delay(400);
  assert.equal(await js("return document.querySelectorAll('.treemap-cell[data-kind=folder]').length"),6,'Reset returns to root');
  console.log('PASS: five colour modes, three nested levels, invalid depth rejection, size filtering, zero-byte list, six distinct folder colours, free-space exclusion, focus details, search highlighting, PNG export, light/dark rendering, keyboard drill-down and reset.');
  await js('document.querySelector(".map-fullscreen-toggle").click()');
  await delay(700);
  assert(await js('return !!document.fullscreenElement'), 'Native fullscreen entered');
  const layout=await js('const panel=document.querySelector(".treemap-panel").getBoundingClientRect();const rail=document.querySelector(".sidebar").getBoundingClientRect();const svg=document.querySelector(".treemap-wrap svg");const box=svg.getBoundingClientRect();return {coverage:panel.width*panel.height/(innerWidth*innerHeight),rail:rail.width,ratio:box.width/box.height,viewRatio:svg.viewBox.baseVal.width/svg.viewBox.baseVal.height,scroll:document.querySelector(".workspace").scrollHeight-document.querySelector(".workspace").clientHeight}');
  assert(layout.coverage>.88,'Map panel occupies approximately 90% of the screen: '+JSON.stringify(layout));
  assert.equal(layout.rail,56,'Explore collapses to an icon rail');
  assert(Math.abs(layout.ratio-layout.viewRatio)<.02,'Map layout fills its container without stretching');
  assert(layout.scroll<=1,'Fullscreen workspace has no vertical overflow');
  assert(await js('return [".map-controls",".map-legend",".map-hint"].every(selector=>document.querySelector(selector).getBoundingClientRect().height>0)'),'Header controls and legend stay visible');
  const fitWidth=await js('return document.querySelector(".treemap-wrap svg").viewBox.baseVal.width');
  await js('document.querySelector(`[aria-label="Zoom in"]`).click()');await delay(250);
  assert(await js('const wrap=document.querySelector(".treemap-wrap");return wrap.scrollWidth>wrap.clientWidth'),'Zoom exposes a scrollable enlarged map');
  assert((await js('return document.querySelector(".treemap-wrap svg").viewBox.baseVal.width'))>fitWidth*1.4,'Zoom increases block geometry');
  await js('document.querySelector(`[aria-label="Fit map"]`).click()');await delay(250);
  assert.equal(await js('return document.querySelector(".treemap-wrap svg").viewBox.baseVal.width'),fitWidth,'Fit restores all blocks');
  await js('document.querySelector(".map-block-list summary").click();document.querySelector(`[aria-label="Inspect empty.txt"]`).focus()');await delay(150);
  assert((await js('return document.querySelector(".map-path").textContent')).endsWith('empty.txt'),'Even zero-size items expose full details in fullscreen');
  await js('document.querySelector(".map-block-list summary").click()');await delay(150);
  await js('document.querySelector(".treemap-cell[data-kind=folder]").dispatchEvent(new MouseEvent("click",{bubbles:true}))');
  await delay(300);
  assert(await js('return document.querySelector(".app-shell").classList.contains("map-fullscreen")'),'Drill-down retains fullscreen');
  await js('document.querySelector(".treemap-cell[data-kind=folder]").dispatchEvent(new MouseEvent("click",{bubbles:true}))');await delay(300);
  await js('document.querySelector(".map-back").click()');await delay(300);
  assert.equal(await js('return document.querySelector(".treemap-panel h2").textContent'),'Games','Fullscreen back returns one folder');
  assert(await js('return !!document.fullscreenElement'),'Back preserves fullscreen');
  await js('document.querySelector(".map-back").click()');await delay(300);
  assert(await js('return document.querySelector(".map-back").disabled'),'Back is disabled at root');
  await js('document.querySelector(".treemap-cell[data-kind=folder]").dispatchEvent(new MouseEvent("click",{bubbles:true}))');await delay(300);
  await js('Array.from(document.querySelectorAll("button")).find(b=>b.textContent.includes("Back to root")).click()');
  await delay(300);
  await fs.writeFile(path.join(__dirname,'../docs/treemap-fullscreen.png'),(await win.webContents.capturePage()).toPNG());
  win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});
  win.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'});
  await delay(600);
  assert(await js('return !document.fullscreenElement&&!document.querySelector(".app-shell").classList.contains("map-fullscreen")'),'Escape restores normal layout');
  await js('document.querySelector(".map-fullscreen-toggle").click()');await delay(500);
  await js('document.querySelector(".map-fullscreen-toggle").click()');await delay(500);
  assert(await js('return !document.fullscreenElement'),'Exit button restores window mode');
  await js('document.querySelector(".map-fullscreen-toggle").click()');await delay(500);
  await js('document.querySelector(".nav-item[aria-label=Overview]").click()');await delay(500);
  assert(await js('return !document.fullscreenElement&&!document.querySelector(".app-shell").classList.contains("map-fullscreen")'),'Leaving Treemap restores full navigation');
  console.log('PASS: fullscreen coverage, compact navigation, proportional layout, visible controls, zoom, small-item details, drill-down, Escape, exit button and navigation exit.');
  app.quit();
}
run().catch(error=>{console.error(error);app.exit(1);});
